# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jac < Formula
  desc "CLI tool for managing people and groups as Infrastructure as Code"
  homepage "https://github.com/nestoca/jac"
  version "0.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/jac/releases/download/v0.0.21/jac_0.0.21_darwin_amd64.tar.gz"
      sha256 "9745ab9118423a04cd9ebe57cc6f15aca66d980c6bff36951c763c05c0a1c760"

      def install
        bin.install "jac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/jac/releases/download/v0.0.21/jac_0.0.21_darwin_arm64.tar.gz"
      sha256 "7c8f5eb60f081a26404c136ff72ec69e2074050750cd04b7f0028d7c77e1ebb2"

      def install
        bin.install "jac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/jac/releases/download/v0.0.21/jac_0.0.21_linux_amd64.tar.gz"
      sha256 "4a7c3a9a037c8d401ad57bfb706111d066e9bee33524d6e8c0d3fadc264995de"

      def install
        bin.install "jac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/jac/releases/download/v0.0.21/jac_0.0.21_linux_arm64.tar.gz"
      sha256 "ea13b6df78b79982604ece4792511a7d0c685c72181e5b75fb5efa650da3a760"

      def install
        bin.install "jac"
      end
    end
  end
end
