# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jac < Formula
  desc "CLI tool for managing people and groups as Infrastructure as Code"
  homepage "https://github.com/nestoca/jac"
  version "0.0.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/jac/releases/download/v0.0.15/jac_0.0.15_darwin_arm64.tar.gz"
      sha256 "dead6eb4c658a872520738de2a4daf369c9fcd0c72e11468d136e42d973fd148"

      def install
        bin.install "jac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/jac/releases/download/v0.0.15/jac_0.0.15_darwin_amd64.tar.gz"
      sha256 "c4bd3ccb2ec413a2273f5a95f4ff6cdbba635801c21e18fa1be6a05fbe7df483"

      def install
        bin.install "jac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/jac/releases/download/v0.0.15/jac_0.0.15_linux_arm64.tar.gz"
      sha256 "e7892ebb021cdd34b6e37a92d8719016a887329db72dec0be0a050bc11bc256e"

      def install
        bin.install "jac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/jac/releases/download/v0.0.15/jac_0.0.15_linux_amd64.tar.gz"
      sha256 "d77db34058ce77d832427eae6528cebc07a863557a766397dd997cee19faf8d4"

      def install
        bin.install "jac"
      end
    end
  end
end
