# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jac < Formula
  desc "CLI tool for managing people and groups as Infrastructure as Code"
  homepage "https://github.com/nestoca/jac"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/jac/releases/download/v0.0.18/jac_0.0.18_darwin_amd64.tar.gz"
      sha256 "bd9f87f6106efc5184d1ad7aebe6001792b17e018a193329893fe8cecef16da0"

      def install
        bin.install "jac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/jac/releases/download/v0.0.18/jac_0.0.18_darwin_arm64.tar.gz"
      sha256 "582fee72faccf247b8577abfa3e7eea50ee259a43b0179a40666cd57a27a012b"

      def install
        bin.install "jac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/jac/releases/download/v0.0.18/jac_0.0.18_linux_arm64.tar.gz"
      sha256 "b45344deecd9584811029009e1ee2f5ffec5dee2f61000d420a9e7a5a4e6d3da"

      def install
        bin.install "jac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/jac/releases/download/v0.0.18/jac_0.0.18_linux_amd64.tar.gz"
      sha256 "e2e1de93487af4b6ca1194245d67a4d3f4dc0468e1553b72b2c6f6c69ebb0afa"

      def install
        bin.install "jac"
      end
    end
  end
end
