# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joy < Formula
  desc "A CLI for happily managing and deploying applications"
  homepage "https://github.com/nestoca/joy"
  version "0.82.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/joy/releases/download/v0.82.0/joy_0.82.0_darwin_amd64.tar.gz"
      sha256 "4982dc917f7ccf41de356360cb8455a05d68eb88bdeaf97c42f26f63d53537f6"

      define_method(:install) do
        bin.install "joy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/joy/releases/download/v0.82.0/joy_0.82.0_darwin_arm64.tar.gz"
      sha256 "026f10e6a9c4b4193055622def2113ddfe8b8a72011d0143af8859fa8e16d27f"

      define_method(:install) do
        bin.install "joy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/joy/releases/download/v0.82.0/joy_0.82.0_linux_amd64.tar.gz"
      sha256 "a9e7d6628927c6e562385e806f8764c30d03246f903a3cad0d95e897523e6efd"
      define_method(:install) do
        bin.install "joy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/joy/releases/download/v0.82.0/joy_0.82.0_linux_arm64.tar.gz"
      sha256 "1f9567f30c6ab3f28cc04482b3c6bd8c048df34787728fb428d98a7ecf1d8545"
      define_method(:install) do
        bin.install "joy"
      end
    end
  end
end
