# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joy < Formula
  desc "A CLI for happily managing and deploying applications"
  homepage "https://github.com/nestoca/joy"
  version "0.41.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/joy/releases/download/v0.41.2/joy_0.41.2_darwin_amd64.tar.gz"
      sha256 "ec2b7538fca0fcd466ea6fd4b5cf4c0ce63e6071c277a81adac133b7be35c024"

      def install
        bin.install "joy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/joy/releases/download/v0.41.2/joy_0.41.2_darwin_arm64.tar.gz"
      sha256 "c94ab4ffda5d172c9bc3642f2841b8b1d8ee116ed86daa5e5ece8292ff117834"

      def install
        bin.install "joy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/joy/releases/download/v0.41.2/joy_0.41.2_linux_arm64.tar.gz"
      sha256 "faa0ba9116788126cba8ffaa4e45c408690d6fe38650396be0ceb6a0c3e6ab00"

      def install
        bin.install "joy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/joy/releases/download/v0.41.2/joy_0.41.2_linux_amd64.tar.gz"
      sha256 "8d6c5c4af40ddd1dfebc4b11d82b5ba47a957d7d43cebdbcfd8c9b6df06ef11e"

      def install
        bin.install "joy"
      end
    end
  end
end
