# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joy < Formula
  desc "A CLI for happily managing and deploying applications"
  homepage "https://github.com/nestoca/joy"
  version "0.29.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/joy/releases/download/v0.29.0/joy_0.29.0_darwin_amd64.tar.gz"
      sha256 "99e24d264b60959ceaee04be8dcf2af5dc3d55586651ac9f021c9cde8430c2c8"

      def install
        bin.install "joy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/joy/releases/download/v0.29.0/joy_0.29.0_darwin_arm64.tar.gz"
      sha256 "8373ceef0dcccc5edd03ee7e37c366270a59444f954b508deee5d95943b767f0"

      def install
        bin.install "joy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/joy/releases/download/v0.29.0/joy_0.29.0_linux_arm64.tar.gz"
      sha256 "6de74cba247448c1d392c56b54103d8468f03cb8a1c8e06845abb5e31ec64173"

      def install
        bin.install "joy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/joy/releases/download/v0.29.0/joy_0.29.0_linux_amd64.tar.gz"
      sha256 "873d71491a79c20a85826fd979b63b97d4abfd093cbc29dacef070ab155eeddc"

      def install
        bin.install "joy"
      end
    end
  end
end
